2024-09-18 19:05:41,354 - ERROR - Exception calling application: [Errno 22] Invalid argument: 'data/new_request/2024-09-18 19:05:41.354194.png'
Traceback (most recent call last):
  File "D:\Projects\django-project\plant-detection\server\.venv\Lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\app.py", line 35, in ClassifyDisease
    with open(image_path, "wb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'data/new_request/2024-09-18 19:05:41.354194.png'
2024-09-18 19:05:47,356 - ERROR - Exception calling application: [Errno 22] Invalid argument: 'data/new_request/2024-09-18 19:05:47.356832.png'
Traceback (most recent call last):
  File "D:\Projects\django-project\plant-detection\server\.venv\Lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\app.py", line 35, in ClassifyDisease
    with open(image_path, "wb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'data/new_request/2024-09-18 19:05:47.356832.png'
2024-09-18 20:09:12,842 - INFO - Image saved at data/new_request/2024-09-18_20-09-12
2024-09-18 20:09:13,097 - INFO - Loading model from Predict/models/caulidetect.pth
2024-09-18 20:09:13,168 - INFO - Model loaded successfully.
2024-09-18 20:09:13,302 - INFO - Loading model from Predict/models/caulidisease.pth
2024-09-18 20:09:13,352 - INFO - Model loaded successfully.
2024-09-18 20:09:13,390 - DEBUG - Importing BlpImagePlugin
2024-09-18 20:09:13,392 - DEBUG - Importing BmpImagePlugin
2024-09-18 20:09:13,392 - DEBUG - Importing BufrStubImagePlugin
2024-09-18 20:09:13,392 - DEBUG - Importing CurImagePlugin
2024-09-18 20:09:13,392 - DEBUG - Importing DcxImagePlugin
2024-09-18 20:09:13,401 - DEBUG - Importing DdsImagePlugin
2024-09-18 20:09:13,407 - DEBUG - Importing EpsImagePlugin
2024-09-18 20:09:13,407 - DEBUG - Importing FitsImagePlugin
2024-09-18 20:09:13,407 - DEBUG - Importing FliImagePlugin
2024-09-18 20:09:13,415 - DEBUG - Importing FpxImagePlugin
2024-09-18 20:09:13,415 - DEBUG - Image: failed to import FpxImagePlugin: No module named 'olefile'
2024-09-18 20:09:13,415 - DEBUG - Importing FtexImagePlugin
2024-09-18 20:09:13,415 - DEBUG - Importing GbrImagePlugin
2024-09-18 20:09:13,419 - DEBUG - Importing GifImagePlugin
2024-09-18 20:09:13,419 - DEBUG - Importing GribStubImagePlugin
2024-09-18 20:09:13,419 - DEBUG - Importing Hdf5StubImagePlugin
2024-09-18 20:09:13,423 - DEBUG - Importing IcnsImagePlugin
2024-09-18 20:09:13,423 - DEBUG - Importing IcoImagePlugin
2024-09-18 20:09:13,423 - DEBUG - Importing ImImagePlugin
2024-09-18 20:09:13,423 - DEBUG - Importing ImtImagePlugin
2024-09-18 20:09:13,423 - DEBUG - Importing IptcImagePlugin
2024-09-18 20:09:13,423 - DEBUG - Importing JpegImagePlugin
2024-09-18 20:09:13,423 - DEBUG - Importing Jpeg2KImagePlugin
2024-09-18 20:09:13,423 - DEBUG - Importing McIdasImagePlugin
2024-09-18 20:09:13,423 - DEBUG - Importing MicImagePlugin
2024-09-18 20:09:13,439 - DEBUG - Image: failed to import MicImagePlugin: No module named 'olefile'
2024-09-18 20:09:13,439 - DEBUG - Importing MpegImagePlugin
2024-09-18 20:09:13,439 - DEBUG - Importing MpoImagePlugin
2024-09-18 20:09:13,439 - DEBUG - Importing MspImagePlugin
2024-09-18 20:09:13,439 - DEBUG - Importing PalmImagePlugin
2024-09-18 20:09:13,439 - DEBUG - Importing PcdImagePlugin
2024-09-18 20:09:13,439 - DEBUG - Importing PcxImagePlugin
2024-09-18 20:09:13,439 - DEBUG - Importing PdfImagePlugin
2024-09-18 20:09:13,455 - DEBUG - Importing PixarImagePlugin
2024-09-18 20:09:13,455 - DEBUG - Importing PngImagePlugin
2024-09-18 20:09:13,455 - DEBUG - Importing PpmImagePlugin
2024-09-18 20:09:13,455 - DEBUG - Importing PsdImagePlugin
2024-09-18 20:09:13,455 - DEBUG - Importing QoiImagePlugin
2024-09-18 20:09:13,455 - DEBUG - Importing SgiImagePlugin
2024-09-18 20:09:13,455 - DEBUG - Importing SpiderImagePlugin
2024-09-18 20:09:13,455 - DEBUG - Importing SunImagePlugin
2024-09-18 20:09:13,455 - DEBUG - Importing TgaImagePlugin
2024-09-18 20:09:13,470 - DEBUG - Importing TiffImagePlugin
2024-09-18 20:09:13,470 - DEBUG - Importing WebPImagePlugin
2024-09-18 20:09:13,613 - DEBUG - Importing WmfImagePlugin
2024-09-18 20:09:13,613 - DEBUG - Importing XbmImagePlugin
2024-09-18 20:09:13,613 - DEBUG - Importing XpmImagePlugin
2024-09-18 20:09:13,613 - DEBUG - Importing XVThumbImagePlugin
2024-09-18 20:09:13,629 - ERROR - Error loading image: cannot identify image file 'D:\\Projects\\django-project\\plant-detection\\server\\data\\new_request\\2024-09-18_20-09-12'
2024-09-18 20:09:13,629 - ERROR - Exception calling application: list indices must be integers or slices, not NoneType
Traceback (most recent call last):
  File "D:\Projects\django-project\plant-detection\server\.venv\Lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\app.py", line 33, in ClassifyDisease
    status, result = disease_service.classify_disease()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\services\disease_service.py", line 33, in classify_disease
    vegetable_status, disease = detector.detect()
                                ^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\Predict\PlantDisease.py", line 50, in detect
    return True, disease_names[disease_class]
                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not NoneType
2024-09-18 20:11:54,884 - INFO - Image saved at data/new_request/2024-09-18_20-11-54
2024-09-18 20:11:55,005 - INFO - Loading model from Predict/models/caulidetect.pth
2024-09-18 20:11:55,102 - INFO - Model loaded successfully.
2024-09-18 20:11:55,239 - INFO - Loading model from Predict/models/caulidisease.pth
2024-09-18 20:11:55,392 - INFO - Model loaded successfully.
2024-09-18 20:11:55,414 - DEBUG - Importing BlpImagePlugin
2024-09-18 20:11:55,416 - DEBUG - Importing BmpImagePlugin
2024-09-18 20:11:55,416 - DEBUG - Importing BufrStubImagePlugin
2024-09-18 20:11:55,416 - DEBUG - Importing CurImagePlugin
2024-09-18 20:11:55,417 - DEBUG - Importing DcxImagePlugin
2024-09-18 20:11:55,418 - DEBUG - Importing DdsImagePlugin
2024-09-18 20:11:55,419 - DEBUG - Importing EpsImagePlugin
2024-09-18 20:11:55,421 - DEBUG - Importing FitsImagePlugin
2024-09-18 20:11:55,421 - DEBUG - Importing FliImagePlugin
2024-09-18 20:11:55,422 - DEBUG - Importing FpxImagePlugin
2024-09-18 20:11:55,423 - DEBUG - Image: failed to import FpxImagePlugin: No module named 'olefile'
2024-09-18 20:11:55,423 - DEBUG - Importing FtexImagePlugin
2024-09-18 20:11:55,423 - DEBUG - Importing GbrImagePlugin
2024-09-18 20:11:55,423 - DEBUG - Importing GifImagePlugin
2024-09-18 20:11:55,423 - DEBUG - Importing GribStubImagePlugin
2024-09-18 20:11:55,424 - DEBUG - Importing Hdf5StubImagePlugin
2024-09-18 20:11:55,424 - DEBUG - Importing IcnsImagePlugin
2024-09-18 20:11:55,427 - DEBUG - Importing IcoImagePlugin
2024-09-18 20:11:55,429 - DEBUG - Importing ImImagePlugin
2024-09-18 20:11:55,429 - DEBUG - Importing ImtImagePlugin
2024-09-18 20:11:55,430 - DEBUG - Importing IptcImagePlugin
2024-09-18 20:11:55,432 - DEBUG - Importing JpegImagePlugin
2024-09-18 20:11:55,432 - DEBUG - Importing Jpeg2KImagePlugin
2024-09-18 20:11:55,432 - DEBUG - Importing McIdasImagePlugin
2024-09-18 20:11:55,433 - DEBUG - Importing MicImagePlugin
2024-09-18 20:11:55,434 - DEBUG - Image: failed to import MicImagePlugin: No module named 'olefile'
2024-09-18 20:11:55,434 - DEBUG - Importing MpegImagePlugin
2024-09-18 20:11:55,435 - DEBUG - Importing MpoImagePlugin
2024-09-18 20:11:55,437 - DEBUG - Importing MspImagePlugin
2024-09-18 20:11:55,438 - DEBUG - Importing PalmImagePlugin
2024-09-18 20:11:55,440 - DEBUG - Importing PcdImagePlugin
2024-09-18 20:11:55,442 - DEBUG - Importing PcxImagePlugin
2024-09-18 20:11:55,442 - DEBUG - Importing PdfImagePlugin
2024-09-18 20:11:55,457 - DEBUG - Importing PixarImagePlugin
2024-09-18 20:11:55,457 - DEBUG - Importing PngImagePlugin
2024-09-18 20:11:55,457 - DEBUG - Importing PpmImagePlugin
2024-09-18 20:11:55,457 - DEBUG - Importing PsdImagePlugin
2024-09-18 20:11:55,457 - DEBUG - Importing QoiImagePlugin
2024-09-18 20:11:55,457 - DEBUG - Importing SgiImagePlugin
2024-09-18 20:11:55,457 - DEBUG - Importing SpiderImagePlugin
2024-09-18 20:11:55,457 - DEBUG - Importing SunImagePlugin
2024-09-18 20:11:55,465 - DEBUG - Importing TgaImagePlugin
2024-09-18 20:11:55,465 - DEBUG - Importing TiffImagePlugin
2024-09-18 20:11:55,465 - DEBUG - Importing WebPImagePlugin
2024-09-18 20:11:55,465 - DEBUG - Importing WmfImagePlugin
2024-09-18 20:11:55,465 - DEBUG - Importing XbmImagePlugin
2024-09-18 20:11:55,465 - DEBUG - Importing XpmImagePlugin
2024-09-18 20:11:55,465 - DEBUG - Importing XVThumbImagePlugin
2024-09-18 20:11:55,465 - ERROR - Error loading image: cannot identify image file 'D:\\Projects\\django-project\\plant-detection\\server\\data\\new_request\\2024-09-18_20-11-54'
2024-09-18 20:11:55,473 - ERROR - Exception calling application: list indices must be integers or slices, not NoneType
Traceback (most recent call last):
  File "D:\Projects\django-project\plant-detection\server\.venv\Lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\app.py", line 33, in ClassifyDisease
    status, result = disease_service.classify_disease()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\services\disease_service.py", line 33, in classify_disease
    vegetable_status, disease = detector.detect()
                                ^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\Predict\PlantDisease.py", line 54, in detect
    return True, disease_names[disease_class]
                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not NoneType
2024-09-18 20:12:57,724 - INFO - Image saved at data/new_request/2024-09-18_20-12-57.png
2024-09-18 20:12:57,789 - INFO - Loading model from Predict/models/caulidetect.pth
2024-09-18 20:12:57,813 - INFO - Model loaded successfully.
2024-09-18 20:12:57,867 - INFO - Loading model from Predict/models/caulidisease.pth
2024-09-18 20:12:57,894 - INFO - Model loaded successfully.
2024-09-18 20:12:57,901 - DEBUG - Importing BlpImagePlugin
2024-09-18 20:12:57,902 - DEBUG - Importing BmpImagePlugin
2024-09-18 20:12:57,902 - DEBUG - Importing BufrStubImagePlugin
2024-09-18 20:12:57,902 - DEBUG - Importing CurImagePlugin
2024-09-18 20:12:57,903 - DEBUG - Importing DcxImagePlugin
2024-09-18 20:12:57,903 - DEBUG - Importing DdsImagePlugin
2024-09-18 20:12:57,906 - DEBUG - Importing EpsImagePlugin
2024-09-18 20:12:57,908 - DEBUG - Importing FitsImagePlugin
2024-09-18 20:12:57,909 - DEBUG - Importing FliImagePlugin
2024-09-18 20:12:57,910 - DEBUG - Importing FpxImagePlugin
2024-09-18 20:12:57,910 - DEBUG - Image: failed to import FpxImagePlugin: No module named 'olefile'
2024-09-18 20:12:57,910 - DEBUG - Importing FtexImagePlugin
2024-09-18 20:12:57,911 - DEBUG - Importing GbrImagePlugin
2024-09-18 20:12:57,911 - DEBUG - Importing GifImagePlugin
2024-09-18 20:12:57,911 - DEBUG - Importing GribStubImagePlugin
2024-09-18 20:12:57,912 - DEBUG - Importing Hdf5StubImagePlugin
2024-09-18 20:12:57,912 - DEBUG - Importing IcnsImagePlugin
2024-09-18 20:12:57,913 - DEBUG - Importing IcoImagePlugin
2024-09-18 20:12:57,914 - DEBUG - Importing ImImagePlugin
2024-09-18 20:12:57,915 - DEBUG - Importing ImtImagePlugin
2024-09-18 20:12:57,915 - DEBUG - Importing IptcImagePlugin
2024-09-18 20:12:57,916 - DEBUG - Importing JpegImagePlugin
2024-09-18 20:12:57,916 - DEBUG - Importing Jpeg2KImagePlugin
2024-09-18 20:12:57,916 - DEBUG - Importing McIdasImagePlugin
2024-09-18 20:12:57,916 - DEBUG - Importing MicImagePlugin
2024-09-18 20:12:57,916 - DEBUG - Image: failed to import MicImagePlugin: No module named 'olefile'
2024-09-18 20:12:57,916 - DEBUG - Importing MpegImagePlugin
2024-09-18 20:12:57,916 - DEBUG - Importing MpoImagePlugin
2024-09-18 20:12:57,916 - DEBUG - Importing MspImagePlugin
2024-09-18 20:12:57,916 - DEBUG - Importing PalmImagePlugin
2024-09-18 20:12:57,916 - DEBUG - Importing PcdImagePlugin
2024-09-18 20:12:57,916 - DEBUG - Importing PcxImagePlugin
2024-09-18 20:12:57,916 - DEBUG - Importing PdfImagePlugin
2024-09-18 20:12:57,923 - DEBUG - Importing PixarImagePlugin
2024-09-18 20:12:57,923 - DEBUG - Importing PngImagePlugin
2024-09-18 20:12:57,923 - DEBUG - Importing PpmImagePlugin
2024-09-18 20:12:57,923 - DEBUG - Importing PsdImagePlugin
2024-09-18 20:12:57,923 - DEBUG - Importing QoiImagePlugin
2024-09-18 20:12:57,923 - DEBUG - Importing SgiImagePlugin
2024-09-18 20:12:57,923 - DEBUG - Importing SpiderImagePlugin
2024-09-18 20:12:57,923 - DEBUG - Importing SunImagePlugin
2024-09-18 20:12:57,923 - DEBUG - Importing TgaImagePlugin
2024-09-18 20:12:57,923 - DEBUG - Importing TiffImagePlugin
2024-09-18 20:12:57,923 - DEBUG - Importing WebPImagePlugin
2024-09-18 20:12:57,931 - DEBUG - Importing WmfImagePlugin
2024-09-18 20:12:57,931 - DEBUG - Importing XbmImagePlugin
2024-09-18 20:12:57,931 - DEBUG - Importing XpmImagePlugin
2024-09-18 20:12:57,931 - DEBUG - Importing XVThumbImagePlugin
2024-09-18 20:12:57,931 - ERROR - Error loading image: cannot identify image file 'D:\\Projects\\django-project\\plant-detection\\server\\data\\new_request\\2024-09-18_20-12-57.png'
2024-09-18 20:12:57,939 - ERROR - Exception calling application: list indices must be integers or slices, not NoneType
Traceback (most recent call last):
  File "D:\Projects\django-project\plant-detection\server\.venv\Lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\app.py", line 33, in ClassifyDisease
    status, result = disease_service.classify_disease()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\services\disease_service.py", line 32, in classify_disease
    vegetable_status, disease = detector.detect()
                                ^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\Predict\PlantDisease.py", line 54, in detect
    return True, disease_names[disease_class]
                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not NoneType
2024-09-19 12:33:47,920 - INFO - Image saved at data/new_request/2024-09-19_12-33-47.png
2024-09-19 12:33:48,042 - INFO - Loading model from Predict/models/caulidetect.pth
2024-09-19 12:33:48,137 - INFO - Model loaded successfully.
2024-09-19 12:33:48,191 - INFO - Loading model from Predict/models/caulidisease.pth
2024-09-19 12:33:48,272 - INFO - Model loaded successfully.
2024-09-19 12:33:48,319 - DEBUG - Importing BlpImagePlugin
2024-09-19 12:33:48,322 - DEBUG - Importing BmpImagePlugin
2024-09-19 12:33:48,322 - DEBUG - Importing BufrStubImagePlugin
2024-09-19 12:33:48,323 - DEBUG - Importing CurImagePlugin
2024-09-19 12:33:48,324 - DEBUG - Importing DcxImagePlugin
2024-09-19 12:33:48,327 - DEBUG - Importing DdsImagePlugin
2024-09-19 12:33:48,331 - DEBUG - Importing EpsImagePlugin
2024-09-19 12:33:48,333 - DEBUG - Importing FitsImagePlugin
2024-09-19 12:33:48,335 - DEBUG - Importing FliImagePlugin
2024-09-19 12:33:48,336 - DEBUG - Importing FpxImagePlugin
2024-09-19 12:33:48,338 - DEBUG - Image: failed to import FpxImagePlugin: No module named 'olefile'
2024-09-19 12:33:48,338 - DEBUG - Importing FtexImagePlugin
2024-09-19 12:33:48,340 - DEBUG - Importing GbrImagePlugin
2024-09-19 12:33:48,341 - DEBUG - Importing GifImagePlugin
2024-09-19 12:33:48,341 - DEBUG - Importing GribStubImagePlugin
2024-09-19 12:33:48,342 - DEBUG - Importing Hdf5StubImagePlugin
2024-09-19 12:33:48,343 - DEBUG - Importing IcnsImagePlugin
2024-09-19 12:33:48,349 - DEBUG - Importing IcoImagePlugin
2024-09-19 12:33:48,351 - DEBUG - Importing ImImagePlugin
2024-09-19 12:33:48,353 - DEBUG - Importing ImtImagePlugin
2024-09-19 12:33:48,354 - DEBUG - Importing IptcImagePlugin
2024-09-19 12:33:48,356 - DEBUG - Importing JpegImagePlugin
2024-09-19 12:33:48,356 - DEBUG - Importing Jpeg2KImagePlugin
2024-09-19 12:33:48,356 - DEBUG - Importing McIdasImagePlugin
2024-09-19 12:33:48,357 - DEBUG - Importing MicImagePlugin
2024-09-19 12:33:48,359 - DEBUG - Image: failed to import MicImagePlugin: No module named 'olefile'
2024-09-19 12:33:48,359 - DEBUG - Importing MpegImagePlugin
2024-09-19 12:33:48,360 - DEBUG - Importing MpoImagePlugin
2024-09-19 12:33:48,365 - DEBUG - Importing MspImagePlugin
2024-09-19 12:33:48,367 - DEBUG - Importing PalmImagePlugin
2024-09-19 12:33:48,369 - DEBUG - Importing PcdImagePlugin
2024-09-19 12:33:48,370 - DEBUG - Importing PcxImagePlugin
2024-09-19 12:33:48,370 - DEBUG - Importing PdfImagePlugin
2024-09-19 12:33:48,378 - DEBUG - Importing PixarImagePlugin
2024-09-19 12:33:48,380 - DEBUG - Importing PngImagePlugin
2024-09-19 12:33:48,380 - DEBUG - Importing PpmImagePlugin
2024-09-19 12:33:48,380 - DEBUG - Importing PsdImagePlugin
2024-09-19 12:33:48,381 - DEBUG - Importing QoiImagePlugin
2024-09-19 12:33:48,383 - DEBUG - Importing SgiImagePlugin
2024-09-19 12:33:48,384 - DEBUG - Importing SpiderImagePlugin
2024-09-19 12:33:48,386 - DEBUG - Importing SunImagePlugin
2024-09-19 12:33:48,387 - DEBUG - Importing TgaImagePlugin
2024-09-19 12:33:48,389 - DEBUG - Importing TiffImagePlugin
2024-09-19 12:33:48,389 - DEBUG - Importing WebPImagePlugin
2024-09-19 12:33:48,418 - DEBUG - Importing WmfImagePlugin
2024-09-19 12:33:48,420 - DEBUG - Importing XbmImagePlugin
2024-09-19 12:33:48,423 - DEBUG - Importing XpmImagePlugin
2024-09-19 12:33:48,425 - DEBUG - Importing XVThumbImagePlugin
2024-09-19 12:33:48,427 - ERROR - Error loading image: cannot identify image file 'D:\\Projects\\django-project\\plant-detection\\server\\data\\new_request\\2024-09-19_12-33-47.png'
2024-09-19 12:33:48,436 - ERROR - Exception calling application: list indices must be integers or slices, not NoneType
Traceback (most recent call last):
  File "D:\Projects\django-project\plant-detection\server\.venv\Lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\app.py", line 33, in ClassifyDisease
    status, result = disease_service.classify_disease()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\services\disease_service.py", line 32, in classify_disease
    vegetable_status, disease = detector.detect()
                                ^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\Predict\PlantDisease.py", line 55, in detect
    return True, disease_names[disease_class]
                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not NoneType
2024-09-19 12:35:26,596 - INFO - Image saved at data/new_request/2024-09-19_12-35-26.png
2024-09-19 12:35:26,676 - INFO - Loading model from Predict/models/caulidetect.pth
2024-09-19 12:35:26,706 - INFO - Model loaded successfully.
2024-09-19 12:35:26,772 - INFO - Loading model from Predict/models/caulidisease.pth
2024-09-19 12:35:26,818 - INFO - Model loaded successfully.
2024-09-19 12:35:26,823 - ERROR - Error loading image: cannot identify image file 'D:\\Projects\\django-project\\plant-detection\\server\\data\\new_request\\2024-09-19_12-35-26.png'
2024-09-19 12:35:26,829 - ERROR - Exception calling application: list indices must be integers or slices, not NoneType
Traceback (most recent call last):
  File "D:\Projects\django-project\plant-detection\server\.venv\Lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\app.py", line 33, in ClassifyDisease
    status, result = disease_service.classify_disease()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\services\disease_service.py", line 32, in classify_disease
    vegetable_status, disease = detector.detect()
                                ^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\Predict\PlantDisease.py", line 55, in detect
    return True, disease_names[disease_class]
                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not NoneType
2024-09-19 12:39:07,438 - INFO - Image saved at data/new_request/2024_09_19_12_39_07.png
2024-09-19 12:39:07,518 - INFO - Loading model from Predict/models/caulidetect.pth
2024-09-19 12:39:07,564 - INFO - Model loaded successfully.
2024-09-19 12:39:07,640 - INFO - Loading model from Predict/models/caulidisease.pth
2024-09-19 12:39:07,661 - INFO - Model loaded successfully.
2024-09-19 12:39:07,718 - INFO - Image loaded and transformed from data/new_request/2024_09_19_12_39_07.png
2024-09-19 12:39:07,871 - ERROR - Predicted class: True
2024-09-19 12:39:07,871 - ERROR - Exception calling application: module 'utils.file_mover' has no attribute 'move_image'
Traceback (most recent call last):
  File "D:\Projects\django-project\plant-detection\server\.venv\Lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\app.py", line 33, in ClassifyDisease
    status, result = disease_service.classify_disease()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\services\disease_service.py", line 35, in classify_disease
    file_mover.move_image(image_path, self.vegetable, 'invalid')
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'utils.file_mover' has no attribute 'move_image'
2024-09-19 12:39:16,527 - INFO - Image saved at data/new_request/2024_09_19_12_39_16.png
2024-09-19 12:39:16,612 - INFO - Loading model from Predict/models/caulidetect.pth
2024-09-19 12:39:16,638 - INFO - Model loaded successfully.
2024-09-19 12:39:16,695 - INFO - Loading model from Predict/models/caulidisease.pth
2024-09-19 12:39:16,723 - INFO - Model loaded successfully.
2024-09-19 12:39:16,739 - INFO - Image loaded and transformed from data/new_request/2024_09_19_12_39_16.png
2024-09-19 12:39:16,832 - ERROR - Predicted class: True
2024-09-19 12:39:16,833 - ERROR - Exception calling application: module 'utils.file_mover' has no attribute 'move_image'
Traceback (most recent call last):
  File "D:\Projects\django-project\plant-detection\server\.venv\Lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\app.py", line 33, in ClassifyDisease
    status, result = disease_service.classify_disease()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\services\disease_service.py", line 35, in classify_disease
    file_mover.move_image(image_path, self.vegetable, 'invalid')
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'utils.file_mover' has no attribute 'move_image'
2024-09-19 12:42:08,564 - INFO - Image saved at data/new_request/2024_09_19_12_42_08.png
2024-09-19 12:42:08,636 - INFO - Loading model from Predict/models/caulidetect.pth
2024-09-19 12:42:08,669 - INFO - Model loaded successfully.
2024-09-19 12:42:08,813 - INFO - Loading model from Predict/models/caulidisease.pth
2024-09-19 12:42:08,840 - INFO - Model loaded successfully.
2024-09-19 12:42:08,865 - INFO - Image loaded and transformed from data/new_request/2024_09_19_12_42_08.png
2024-09-19 12:42:08,923 - ERROR - Predicted class: True
2024-09-19 12:42:08,923 - ERROR - Exception calling application: module 'utils.file_mover' has no attribute 'move_image'
Traceback (most recent call last):
  File "D:\Projects\django-project\plant-detection\server\.venv\Lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\app.py", line 33, in ClassifyDisease
    status, result = disease_service.classify_disease()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\django-project\plant-detection\server\services\disease_service.py", line 35, in classify_disease
    file_mover.move_file(image_path, self.vegetable, 'invalid')
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'utils.file_mover' has no attribute 'move_image'
2024-09-19 12:42:13,982 - INFO - Image saved at data/new_request/2024_09_19_12_42_13.png
2024-09-19 12:42:14,081 - INFO - Loading model from Predict/models/caulidetect.pth
2024-09-19 12:42:14,105 - INFO - Model loaded successfully.
2024-09-19 12:42:14,155 - INFO - Loading model from Predict/models/caulidisease.pth
2024-09-19 12:42:14,178 - INFO - Model loaded successfully.
2024-09-19 12:42:14,203 - INFO - Image loaded and transformed from data/new_request/2024_09_19_12_42_13.png
2024-09-19 12:42:14,267 - ERROR - Predicted class: True
2024-09-19 12:42:14,268 - INFO - image moved to data/predicted_data\cauliflower\invalid
2024-09-19 12:44:09,448 - INFO - Image saved at data/new_request/2024_09_19_12_44_09.png
2024-09-19 12:44:09,548 - INFO - Loading model from Predict/models/caulidetect.pth
2024-09-19 12:44:09,588 - INFO - Model loaded successfully.
2024-09-19 12:44:09,681 - INFO - Loading model from Predict/models/caulidisease.pth
2024-09-19 12:44:09,727 - INFO - Model loaded successfully.
2024-09-19 12:44:09,743 - INFO - Image loaded and transformed from data/new_request/2024_09_19_12_44_09.png
2024-09-19 12:44:09,873 - INFO - image moved to data/predicted_data\cauliflower\Downy Mildew
2024-09-19 12:44:18,652 - INFO - Image saved at data/new_request/2024_09_19_12_44_18.png
2024-09-19 12:44:18,749 - INFO - Loading model from Predict/models/caulidetect.pth
2024-09-19 12:44:18,799 - INFO - Model loaded successfully.
2024-09-19 12:44:18,941 - INFO - Loading model from Predict/models/caulidisease.pth
2024-09-19 12:44:18,970 - INFO - Model loaded successfully.
2024-09-19 12:44:18,980 - INFO - Image loaded and transformed from data/new_request/2024_09_19_12_44_18.png
2024-09-19 12:44:19,094 - INFO - image moved to data/predicted_data\cauliflower\Downy Mildew
2024-09-19 12:44:20,184 - INFO - Image saved at data/new_request/2024_09_19_12_44_20.png
2024-09-19 12:44:20,282 - INFO - Loading model from Predict/models/caulidetect.pth
2024-09-19 12:44:20,327 - INFO - Model loaded successfully.
2024-09-19 12:44:20,397 - INFO - Loading model from Predict/models/caulidisease.pth
2024-09-19 12:44:20,446 - INFO - Model loaded successfully.
2024-09-19 12:44:20,464 - INFO - Image loaded and transformed from data/new_request/2024_09_19_12_44_20.png
2024-09-19 12:44:20,614 - INFO - image moved to data/predicted_data\cauliflower\Downy Mildew
2024-09-19 12:47:08,352 - INFO - Image saved at data/new_request/2024_09_19_12_47_08.png
2024-09-19 12:47:08,422 - INFO - Loading model from Predict/models/caulidetect.pth
2024-09-19 12:47:08,453 - INFO - Model loaded successfully.
2024-09-19 12:47:08,503 - INFO - Loading model from Predict/models/caulidisease.pth
2024-09-19 12:47:08,525 - INFO - Model loaded successfully.
2024-09-19 12:47:08,546 - INFO - Image loaded and transformed from data/new_request/2024_09_19_12_47_08.png
2024-09-19 12:47:08,636 - INFO - image moved to data/predicted_data\cauliflower\Downy Mildew
2024-09-19 12:47:10,394 - INFO - Image saved at data/new_request/2024_09_19_12_47_10.png
2024-09-19 12:47:10,501 - INFO - Loading model from Predict/models/caulidetect.pth
2024-09-19 12:47:10,539 - INFO - Model loaded successfully.
2024-09-19 12:47:10,629 - INFO - Loading model from Predict/models/caulidisease.pth
2024-09-19 12:47:10,667 - INFO - Model loaded successfully.
2024-09-19 12:47:10,688 - INFO - Image loaded and transformed from data/new_request/2024_09_19_12_47_10.png
2024-09-19 12:47:10,811 - INFO - image moved to data/predicted_data\cauliflower\Downy Mildew
2024-09-19 12:47:11,801 - INFO - Image saved at data/new_request/2024_09_19_12_47_11.png
2024-09-19 12:47:11,910 - INFO - Loading model from Predict/models/caulidetect.pth
2024-09-19 12:47:11,961 - INFO - Model loaded successfully.
2024-09-19 12:47:12,052 - INFO - Loading model from Predict/models/caulidisease.pth
2024-09-19 12:47:12,105 - INFO - Model loaded successfully.
2024-09-19 12:47:12,122 - INFO - Image loaded and transformed from data/new_request/2024_09_19_12_47_11.png
2024-09-19 12:47:12,232 - INFO - image moved to data/predicted_data\cauliflower\Downy Mildew
2024-09-19 12:47:14,496 - INFO - Image saved at data/new_request/2024_09_19_12_47_14.png
2024-09-19 12:47:14,601 - INFO - Loading model from Predict/models/caulidetect.pth
2024-09-19 12:47:14,635 - INFO - Model loaded successfully.
2024-09-19 12:47:14,698 - INFO - Loading model from Predict/models/caulidisease.pth
2024-09-19 12:47:14,724 - INFO - Model loaded successfully.
2024-09-19 12:47:14,734 - INFO - Image loaded and transformed from data/new_request/2024_09_19_12_47_14.png
2024-09-19 12:47:14,833 - INFO - image moved to data/predicted_data\cauliflower\Downy Mildew
2024-09-19 12:47:15,789 - INFO - Image saved at data/new_request/2024_09_19_12_47_15.png
2024-09-19 12:47:15,890 - INFO - Loading model from Predict/models/caulidetect.pth
2024-09-19 12:47:15,939 - INFO - Model loaded successfully.
2024-09-19 12:47:16,032 - INFO - Loading model from Predict/models/caulidisease.pth
2024-09-19 12:47:16,078 - INFO - Model loaded successfully.
2024-09-19 12:47:16,097 - INFO - Image loaded and transformed from data/new_request/2024_09_19_12_47_15.png
2024-09-19 12:47:16,219 - INFO - image moved to data/predicted_data\cauliflower\Downy Mildew
